In [2]:
import pandas as pd
import seaborn as sns

In [11]:
df=sns.load_dataset("datasets/planets")
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [12]:
df.tail()

       method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

# Grouping

In [15]:
df.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [17]:
df['method'].value_counts()

method
Radial Velocity                  553
Transit                          397
Imaging                           38
Microlensing                      23
Eclipse Timing Variations          9
Pulsar Timing                      5
Transit Timing Variations          4
Orbital Brightness Modulation      3
Astrometry                         2
Pulsation Timing Variations        1
Name: count, dtype: int64

In [25]:
df.isnull().any()

method            False
number            False
orbital_period     True
mass               True
distance           True
year              False
dtype: bool

In [18]:
df['method'].isnull().any()

False

In [23]:
unique_vals=df['method'].unique()
unique_vals

array(['Radial Velocity', 'Imaging', 'Eclipse Timing Variations',
       'Transit', 'Astrometry', 'Transit Timing Variations',
       'Orbital Brightness Modulation', 'Microlensing', 'Pulsar Timing',
       'Pulsation Timing Variations'], dtype=object)

In [24]:
len(unique_vals)

10

In [27]:
df['distance'].value_counts(dropna=False)

distance
NaN       227
780.00      7
613.00      6
12.83       6
303.00      6
         ...
99.40       1
18.21       1
37.78       1
20.98       1
293.00      1
Name: count, Length: 553, dtype: int64

In [28]:
df['distance'].isnull().any()

True

In [29]:
df['distance'].isnull().sum()

227

In [30]:
df.groupby('method')

In [31]:
df.groupby('method').mean()

,number,orbital_period,mass,distance,year
method,,,,,
Astrometry,1.000000,631.180000,NaN,17.875000,2011.500000
Eclipse Timing Variations,1.666667,4751.644444,5.125000,315.360000,2010.000000
Imaging,1.315789,118247.737500,NaN,67.715937,2009.131579
Microlensing,1.173913,3153.571429,NaN,4144.000000,2009.782609
Orbital Brightness Modulation,1.666667,0.709307,NaN,1180.000000,2011.666667
Pulsar Timing,2.200000,7343.021201,NaN,1200.000000,1998.400000
Pulsation Timing Variations,1.000000,1170.000000,NaN,NaN,2007.000000
Radial Velocity,1.721519,823.354680,2.630699,51.600208,2007.518987
Transit,1.954660,21.102073,1.470000,599.298080,2011.236776
Transit Timing Variations,2.250000,79.783500,NaN,1104.333333,2012.500000

In [32]:
df.groupby('method')['distance']

In [33]:
df.groupby('method')['distance'].mean()

method
Astrometry                         17.875000
Eclipse Timing Variations         315.360000
Imaging                            67.715937
Microlensing                     4144.000000
Orbital Brightness Modulation    1180.000000
Pulsar Timing                    1200.000000
Pulsation Timing Variations              NaN
Radial Velocity                    51.600208
Transit                           599.298080
Transit Timing Variations        1104.333333
Name: distance, dtype: float64

In [35]:
df.groupby('method')['distance'].median()

method
Astrometry                         17.875
Eclipse Timing Variations         315.360
Imaging                            40.395
Microlensing                     3840.000
Orbital Brightness Modulation    1180.000
Pulsar Timing                    1200.000
Pulsation Timing Variations           NaN
Radial Velocity                    40.445
Transit                           341.000
Transit Timing Variations         855.000
Name: distance, dtype: float64

In [40]:
df.groupby('year')['number']

In [39]:
df.groupby('year')['number'].sum()

year
1989      1
1992      6
1994      3
1995      1
1996     15
1997      1
1998     11
1999     24
2000     27
2001     15
2002     46
2003     35
2004     41
2005     64
2006     43
2007     65
2008    120
2009    131
2010    193
2011    354
2012    258
2013    277
2014    117
Name: number, dtype: int64

In [45]:
df[df['year']==2001]

              method  number  orbital_period   mass  distance  year
14   Radial Velocity       3       2391.0000   0.54     14.08  2001
198  Radial Velocity       2        349.7000   1.25     25.64  2001
209  Radial Velocity       1        829.0000   0.80     32.70  2001
211  Radial Velocity       1        431.8800   2.07     77.82  2001
272  Radial Velocity       1        738.4590   2.61     34.60  2001
281  Radial Velocity       1        385.9000   5.59     39.56  2001
299  Radial Velocity       1       2063.8180  10.35     18.21  2001
351  Radial Velocity       1          6.2760   1.90     58.82  2001
371  Radial Velocity       1        111.4357    NaN     29.04  2001
442  Radial Velocity       1        493.7000   1.10     20.43  2001
540  Radial Velocity       1         71.4840   7.03     46.73  2001
593  Radial Velocity       1        951.0000   4.50     40.75  2001

In [49]:
df.groupby('method')['year'].describe()

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,2011.500000,2.121320,2010.0,2010.75,2011.5,2012.25,2013.0
Eclipse Timing Variations,9.0,2010.000000,1.414214,2008.0,2009.00,2010.0,2011.00,2012.0
Imaging,38.0,2009.131579,2.781901,2004.0,2008.00,2009.0,2011.00,2013.0
Microlensing,23.0,2009.782609,2.859697,2004.0,2008.00,2010.0,2012.00,2013.0
Orbital Brightness Modulation,3.0,2011.666667,1.154701,2011.0,2011.00,2011.0,2012.00,2013.0
Pulsar Timing,5.0,1998.400000,8.384510,1992.0,1992.00,1994.0,2003.00,2011.0
Pulsation Timing Variations,1.0,2007.000000,NaN,2007.0,2007.00,2007.0,2007.00,2007.0
Radial Velocity,553.0,2007.518987,4.249052,1989.0,2005.00,2009.0,2011.00,2014.0
Transit,397.0,2011.236776,2.077867,2002.0,2010.00,2012.0,2013.00,2014.0
Transit Timing Variations,4.0,2012.500000,1.290994,2011.0,2011.75,2012.5,2013.25,2014.0

In [61]:
df.groupby('method').aggregate([min,max,sum,'mean','median'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_10932\564616263.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('method').aggregate([min,max,sum,'mean','median'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_10932\564616263.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('method').aggregate([min,max,sum,'mean','median'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_10932\564616263.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('method').aggregate([min,max,sum,'mean','median'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_10932\564616263.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('method').aggregate([min,max,sum,'mean','median'])

                              number                           orbital_period  \
                                 min max  sum      mean median            min
method
Astrometry                         1   1    2  1.000000    1.0     246.360000
Eclipse Timing Variations          1   2   15  1.666667    2.0    1916.250000
Imaging                            1   4   50  1.315789    1.0    4639.150000
Microlensing                       1   2   27  1.173913    1.0    1825.000000
Orbital Brightness Modulation      1   2    5  1.666667    2.0       0.240104
Pulsar Timing                      1   3   11  2.200000    3.0       0.090706
Pulsation Timing Variations        1   1    1  1.000000    1.0    1170.000000
Radial Velocity                    1   6  952  1.721519    1.0       0.736540
Transit                            1   7  776  1.954660    1.0       0.355000
Transit Timing Variations          2   3    9  2.250000    2.0      22.339500

                                                                           \
                                         max           sum           mean
method
Astrometry                       1016.000000  1.262360e+03     631.180000
Eclipse Timing Variations       10220.000000  4.276480e+04    4751.644444
Imaging                        730000.000000  1.418973e+06  118247.737500
Microlensing                     5100.000000  2.207500e+04    3153.571429
Orbital Brightness Modulation       1.544929  2.127920e+00       0.709307
Pulsar Timing                   36525.000000  3.671511e+04    7343.021201
Pulsation Timing Variations      1170.000000  1.170000e+03    1170.000000
Radial Velocity                 17337.500000  4.553151e+05     823.354680
Transit                           331.600590  8.377523e+03      21.102073
Transit Timing Variations         160.000000  2.393505e+02      79.783500

                                             ... distance                      \
                                     median  ...      min      max        sum
method                                       ...
Astrometry                       631.180000  ...    14.98    20.77      35.75
Eclipse Timing Variations       4343.500000  ...   130.72   500.00    1261.44
Imaging                        27500.000000  ...     7.69   165.00    2166.91
Microlensing                    3300.000000  ...  1760.00  7720.00   41440.00
Orbital Brightness Modulation      0.342887  ...  1180.00  1180.00    2360.00
Pulsar Timing                     66.541900  ...  1200.00  1200.00    1200.00
Pulsation Timing Variations     1170.000000  ...      NaN      NaN       0.00
Radial Velocity                  360.200000  ...     1.35   354.00   27348.11
Transit                            5.714932  ...    38.00  8500.00  134242.77
Transit Timing Variations         57.011000  ...   339.00  2119.00    3313.00

                                                      year                 \
                                      mean    median   min   max      sum
method
Astrometry                       17.875000    17.875  2010  2013     4023
Eclipse Timing Variations       315.360000   315.360  2008  2012    18090
Imaging                          67.715937    40.395  2004  2013    76347
Microlensing                   4144.000000  3840.000  2004  2013    46225
Orbital Brightness Modulation  1180.000000  1180.000  2011  2013     6035
Pulsar Timing                  1200.000000  1200.000  1992  2011     9992
Pulsation Timing Variations            NaN       NaN  2007  2007     2007
Radial Velocity                  51.600208    40.445  1989  2014  1110158
Transit                         599.298080   341.000  2002  2014   798461
Transit Timing Variations      1104.333333   855.000  2011  2014     8050


                                      mean  median
method
Astrometry                     2011.500000  2011.5
Eclipse Timing Variations      2010.000000  2010.0
Imaging                        2009.131579  2009.0
Microlensing                   2009.782609  2010.0
Orbital Brightness Modulation  2011.666667  2011.0
Pulsar Timing                  1998.400000  1994.0
Pulsation Timing Variations    2007.000000  2007.0
Radial Velocity                2007.518987  2009.0
Transit                        2011.236776  2012.0
Transit Timing Variations      2012.500000  2012.5

[10 rows x 25 columns]

# Filtering

In [72]:
df.groupby('method').std()

,number,orbital_period,mass,distance,year
method,,,,,
Astrometry,0.000000,544.217663,NaN,4.094148,2.121320
Eclipse Timing Variations,0.500000,2499.130945,1.308148,213.203907,1.414214
Imaging,0.933035,213978.177277,NaN,53.736817,2.781901
Microlensing,0.387553,1113.166333,NaN,2076.611556,2.859697
Orbital Brightness Modulation,0.577350,0.725493,NaN,0.000000,1.154701
Pulsar Timing,1.095445,16313.265573,NaN,NaN,8.384510
Pulsation Timing Variations,NaN,NaN,NaN,NaN,NaN
Radial Velocity,1.157141,1454.926210,3.825883,45.559381,4.249052
Transit,1.399119,46.185893,NaN,913.876990,2.077867
Transit Timing Variations,0.500000,71.599884,NaN,915.819487,1.290994

In [62]:
df.groupby('method').mean()

,number,orbital_period,mass,distance,year
method,,,,,
Astrometry,1.000000,631.180000,NaN,17.875000,2011.500000
Eclipse Timing Variations,1.666667,4751.644444,5.125000,315.360000,2010.000000
Imaging,1.315789,118247.737500,NaN,67.715937,2009.131579
Microlensing,1.173913,3153.571429,NaN,4144.000000,2009.782609
Orbital Brightness Modulation,1.666667,0.709307,NaN,1180.000000,2011.666667
Pulsar Timing,2.200000,7343.021201,NaN,1200.000000,1998.400000
Pulsation Timing Variations,1.000000,1170.000000,NaN,NaN,2007.000000
Radial Velocity,1.721519,823.354680,2.630699,51.600208,2007.518987
Transit,1.954660,21.102073,1.470000,599.298080,2011.236776
Transit Timing Variations,2.250000,79.783500,NaN,1104.333333,2012.500000

In [71]:
def testFunc(a):
    return a['distance'].mean()<1000

df.groupby('method').filter(testFunc)

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[999 rows x 6 columns]